# Generated by Django 3.0.8 on 2020-10-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='股票代码')),
                ('name', models.CharField(max_length=64, verbose_name='股票名称')),
                ('latestPrice', models.CharField(max_length=64, verbose_name='最新股价')),
                ('dataTime', models.CharField(max_length=64, verbose_name='时间')),
            ],
            options={
                'verbose_name': '股票信息',
                'verbose_name_plural': '股票信息',
                'db_table': 'stock_attrs',
            },
        ),
    ]
