# Generated by Django 3.0.8 on 2020-10-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DividendInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='股票代码')),
                ('period', models.CharField(max_length=32, verbose_name='分红信息报告期')),
                ('value', models.CharField(max_length=32, verbose_name='分红信息值')),
                ('title', models.CharField(max_length=256, verbose_name='公告名称')),
                ('noticeDate', models.CharField(max_length=32, verbose_name='交易所公告日期')),
                ('url', models.CharField(max_length=512, verbose_name='公告链接')),
                ('addDate', models.CharField(max_length=32, verbose_name='添加日期')),
                ('valueType', models.CharField(max_length=32, verbose_name='分红信息类型')),
                ('rate', models.CharField(max_length=32, verbose_name='股息率（TTM）')),
                ('stockPrice', models.CharField(max_length=32, verbose_name='股价')),
            ],
            options={
                'verbose_name': '帮我盯着分红信息',
                'verbose_name_plural': '帮我盯着分红信息',
                'db_table': 'dividendinfo',
            },
        ),
    ]
